### ISSUE TITLE
error loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by SampannaKahu** [EOSIO/vt-blockchain-bootcamp-starter#5]
Hi,

I am not able to start blockchain using the ./start_blockchain.sh script.
The command does not finish and infinitely keeps printing:
```
'Waiting for EOSIO blockchain to be started...' 
```
When I checked the logs at blockchain/data/nodeos.log, it says
```
nodeos: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
I am running this on Ubuntu 16.04 and there were no errors in the first time setup script.
Please help.

Thanks!

**Comment by SampannaKahu** [comment]
> If you are running on a VM or on WSL, you have limited computer resources. It could take as long as 5 minutes for the blockchain to start in these restricted environments.

I don't think this is a resource issue since this is running on an i7 8th gen with 16GB RAM. This is also not a VM. I have waited for about 10 minutes for this to come up but still no luck.

However, thanks for agreeing to look into this. Helps a lot.

Regards,
Sampanna.

**Comment by dskvr** [comment]
This should ease your woes 😄 

```
apt install libtinfo5 
```

**Comment by SampannaKahu** [comment]
> This should ease your woes smile
> 
> ```
> apt install libtinfo5 
> ```

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtinfo5 is already the newest version (6.0+20160213-1ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-139 linux-headers-4.4.0-139-generic linux-image-4.4.0-139-generic linux-image-extra-4.4.0-139-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 98 not upgraded.
```

Sorry, no luck there.

**Comment by dskvr** [comment]
@SampannaKahu What platform are you running on?

OS: 
Version:

**Comment by dskvr** [comment]
Apologies, found it 😄

**Comment by dskvr** [comment]
@SampannaKahu Ok, the issue is you're running 16.04. There is a bug in the ubuntu install script that assumes you are running `18.04`.  I've created a branch to address this issue. 

1. First you'll need to uninstall `eosio`

```bash
sudo apt remove eosio
```

2. Second, checkout a the branch with this fix. First navigate to your `vt-blockchain-bootcamp-starter` directory.

```bash
git fetch --all
git checkout --track origin/hotfix/ubuntu-16.04
```

3. Run the script as instructed previously.
```bash
./first_time_setup.sh
```

**Comment by dskvr** [comment]
Reopening this issue for now since this bug is still present in master
